### ISSUE TITLE
bdist_wheel

### ISSUE THREAD

**Issue by vovel** [novemberfiveco/s3pypi#1]
Is there an easy way to upload a wheel package (if c extension exists, complile it and include it in binary distribution) instead of the default source distribution?

I see that in line 38 of s3pypi/package.py, the command that is effectively run is

python setup.py sdist --formats gztar

but what i really want (or at least want to have the option of doing) is

python setup.py bdist_wheel

**Comment by rubenvdb** [comment]
We've added support for bdist_wheel support in the just-released 0.0.8 release.
Let us know if you have any additional remarks or questions!
