### ISSUE TITLE
SSL Certificate - Failure?

### ISSUE THREAD

**Issue by drcoll** [novemberfiveco/s3pypi#12]
I was able to successfully publish packages to S3, and I can go in and view the packages from S3 in the AWS console, but when I try to do a

`pip install {project} --extra-index-url https://pypi.example.com/`

*removed project name and actual url*

I receive the error below:

'''
Could not fetch URL https://pypi.example.com/{project}/: There was a problem confirming the ssl certificate: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581) - skipping
  Could not find a version that satisfies the requirement {project} (from versions: )
No matching distribution found for {project}
'''

I'm not sure if this is indeed a SSL certificate issue, or if this is a `Could not find a version that satisfies the requirement...` issue...

I use `versioneer` for my projects...

Any idea?

I did go an update `pip` and `virtualenv` to the newest versions before attempting.

**Comment by mdwint** [comment]
This is indeed an SSL issue. Do you use CloudFront for serving packages over HTTPS? If not, check out our [tutorial](https://novemberfive.co/blog/opensource-pypi-package-repository-tutorial/).

If the issue persists, make sure you have these packages installed:

`pip install pyOpenSSL ndg-httpsclient pyasn1`  ([more info](http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package))

To disable SSL verification in pip altogether, you can use the `--trusted-host` argument:

`pip install {package} --extra-index-url https://{domain}/ --trusted-host {domain}`

**Comment by drcoll** [comment]
I followed the tutorial to get myself set up, but I just remembered I had to go into your CloudFormation file and use the `AcmCertificateArn` parameter instead of the `ServerCertificateId`... as I didn't upload my own SSL certificate, and it was created with ACM. That was the only thing I altered.

Let me try out `pip install pyOpenSSL ndg-httpsclient pyasn1`.

**Comment by drcoll** [comment]
Issue was due to confusion with the `CNAME` parameter of the CloudFront distribution
