### ISSUE TITLE
Add option for specifying S3 endpoint + credentials

### ISSUE THREAD

**Issue by Faylixe** [novemberfiveco/s3pypi#20]
Thanks for your tool which is awesome. I would like to use it for managing internal company python packages using [Minio](https://github.com/minio/minio), a S3 like server which is 100% compatible with original AWS S3 API. The only thing is that i have to specify the API endpoint to **boto**, or any AWS S3 related tool. I would like to know if you are ok to add following option to the CLI:

- **--endpoint** _URL_
- AWS credentials which are mandatory for uploading to Minio S3.

It would still be compatible with your solution, just adding option parsing and update **boto** resources creation as following :

```python
s3 = boto3.resource('s3',
                    endpoint_url='minio_url',
                    aws_access_key_id='YOUR-ACCESSKEYID',
                    aws_secret_access_key='YOUR-SECRETACCESSKEY',
                    config=Config(signature_version='s3v4'),
                    region_name='us-east-1')
```

If this is not bothering you i would gladly update the tool myself and submit a pull request.

**Comment by LanDeQuHuXi** [comment]
Hi @Faylixe ,

I'm wondering how you guys secure the downloading part (pip install part).
The --secret option is simple but it introduce two problems:
1. this is a plain text pwd
2. if someone leaves the team, we have to migrate the packages to another secret key to protect it if we want to revoke his access to the package

I'm currently thinking adding an IP address constraint to the S3 server, which is definitely not a perfect solution.

It would be appreciated, if you can give me some suggestions.
Thanks!

**Comment by Faylixe** [comment]
Well we actually does not have such security constraint since this is a very small company and such Minio server would not be accessible from outside company's network. Revoking user from the team would only consists to ban it from internal network. But still this is a real issue, the IP address won't be the best one indeed (in our case, pip call will be performed on developper, machine, as well in container through CI build, which can be executed in a wide range of machine in a cluster)

**Comment by LanDeQuHuXi** [comment]
@Faylixe 

I see, actually your approach is essential the same as the constrain IP access.
thanks.

**Comment by Faylixe** [comment]
Yes, except that it is handled outside of s3pypi. That is easier to setup since the Minio S3 server is totally under control and ran into our network.

**Comment by LanDeQuHuXi** [comment]
@Faylixe 
Yes.
actually, by "adding an IP address constraint to the S3 server", I meant the pypi server at AWS S3

So really the same thing.
This is possibly the most easy solution for now.

**Comment by VMois** [comment]
Any updates on adding support for credentials? It would be awesome to specify different profiles during the deployment. As far as I can see no PR was opened.

**Comment by VMois** [comment]
Sorry, just went to the parser code and found `profile` argument. It would be nice to add this to docs.

**Comment by gutomaia** [comment]
It would be really nice to add the options to set specific credentials and endpoints. That would allow the use of other S3 like solutions not hosted in AWS.

**Comment by mdwint** [comment]
#81 adds the `--s3-endpoint-url` option.

Credentials and other options can be passed via [environment variables](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-environment-variables) or the [`~/.aws/config`](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-a-configuration-file) file.
