### ISSUE TITLE
Additional AWS cloud formation template for handling the case of a user using AWS Route 53

### ISSUE THREAD

**Issue by helveticafire** [novemberfiveco/s3pypi#24]
This would eliminate these points for the Route 53 users:
- When finished, click the “Outputs” tab, and copy the value of the “CNAMERecordValue” output parameter.
- Create a CNAME (or alias if you’re using Route 53) record for your subdomain and point it to this Cloudfront distribution (CNAMERecordValue).

**Comment by helveticafire** [comment]
Thanks for this project it worked amazingly but I had to setup the Route 53 not as a CNAME but as an "A - IPv4 Address"

**Comment by mdwint** [comment]
Closing this because the CloudFormation templates have been replaced by a Terraform configuration.
