### ISSUE TITLE
s3pypi cli using invalid keyword argument for argparse.ArgumentParser

### ISSUE THREAD

**Issue by vovel** [novemberfiveco/s3pypi#3]
```
(build) admin@ip-192-168-2-109:~/lxml-3.4.4$ s3pypi --bucket my_bucket
Traceback (most recent call last):
  File "/home/admin/build/bin/s3pypi", line 11, in <module>
    sys.exit(main())
  File "/home/admin/build/lib/python3.5/site-packages/s3pypi/cli.py", line 14, in main
    p = argparse.ArgumentParser(prog=__prog__, version=__version__)
TypeError: __init__() got an unexpected keyword argument 'version'
```

https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser
According to the docs, version is not a valid keyword argument for the argparse.ArgumentParser constructor. Instead, it's supposed to be used within the context of adding an argument, like so:

```
p.add_argument('--version', action='version', version='{} {}'.format(__prog__, __version__))
```

**Comment by pedropregueiro** [comment]
I think this is a python3 issue. I had the same problem, but switching back to python2 seems to make it go away ;)

**Comment by mdwint** [comment]
This is indeed a Python 3 issue. Since s3pypi currently only supports Python 2.7, we're closing #3 and #4 for now.
