### ISSUE TITLE
add an option to specify the aws profile

### ISSUE THREAD

**Issue by onema** [novemberfiveco/s3pypi#30]
This is a feature request to add a `--profile` option to the command line tool so I can specify the AWS profile I want to use.

Currently, this is what I'm getting:

```bash
s3pypi --bucket pypi.mywebsite.com --profile production
usage: s3pypi [-h] --bucket BUCKET [--secret SECRET] [--region REGION]
              [--force] [--no-wheel] [--bare] [--private]
s3pypi: error: unrecognized arguments: --profile production
```

Thank you!

**Comment by mdwint** [comment]
You can pass in the profile through an environment variable:

```AWS_PROFILE=myprofile s3pypi --bucket pypi.mywebsite.com```
