### ISSUE TITLE
Alpha, beta releases are not properly handled

### ISSUE THREAD

**Issue by abunuwas** [novemberfiveco/s3pypi#40]
Alpha or beta releases of a library, in the form of `1.23.0a0` or `1.23.0b0` are wrongly picked up as the release itself by the following line:

https://github.com/novemberfiveco/s3pypi/blob/4851ca304386b7e673f8c652ed4e2fa4c8519901/s3pypi/package.py#L97

The regular expression in that line only considers the case that a releases consists exclusively of digits. 

This means that, if I make a beta release `1.23.0b0` of a library and then want to release `1.23.0`, I can't because `s3pypi` tells me that this version already exists.

Also, the library should provide a way to undo a release. Currently, if I release version `1.23.0b0` and then delete the builds from the s3 bucket, that's not enough to re-release that version because `s3pypi` only looks into the generated html file to check for existing releases.

**Comment by jakul** [comment]
@mdwint This is affecting me too

**Comment by jakul** [comment]
I've dug a little bit deeper and the error is not in the code @abunuwas mentioned, it's in the code which constructs the package name and version when it is _uploading_ to S3.

**Comment by mdwint** [comment]
Version matching was made PEP 0440 compliant in #55.
