### ISSUE TITLE
Allow uploading built files directly

### ISSUE THREAD

**Issue by lepisma** [novemberfiveco/s3pypi#43]
s3pypi `create`s the package using a fixed [command](https://github.com/novemberfiveco/s3pypi/blob/8458d28a9791a134b6335d08b6641de6de55889f/s3pypi/__main__.py#L20) every time it runs. This doesn't work with tools like [poetry](https://github.com/sdispater/poetry) which hide the complexity of `setup.py` and produce dists using a different command (`poetry build`). Can we instead provide an option like `--file <file-to-upload>` (an [example](https://gitlab.com/vernacularai/s3pypi/commit/f70317779ca7f451d404a78dd180da1b40bb628d)) that skips the `create` fn call?

**Comment by username-dot-com** [comment]
I'm not sure if you still need this, but @lepisma I've addressed this issue in [this pr](https://github.com/novemberfiveco/s3pypi/pull/56)

**Comment by lepisma** [comment]
Thanks! Closing this issue.
