### ISSUE TITLE
Cannot figure out how to configure whitelist

### ISSUE THREAD

**Issue by derek-adair** [novemberfiveco/s3pypi#44]
I realize this is likely an issue w/ cloudfront and how to write the config file... but I'm trying to use the s3-pypi-with-waf.json template and its throwing this error:

```An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [WhitelistedCIDRBlock] must have value```

Any attempts at modifying it have not been successful.

**Comment by redblacktree** [comment]
You have to supply the WhitelistedCIDRBlock parameter in addition to the other two (DomainName and  AcmCertificateArn) when you use that cloudformation template.

**Comment by mdwint** [comment]
Closing this because the CloudFormation templates have been replaced by a Terraform configuration.
