### ISSUE TITLE
known boto issue inconsistent with writeup instructions

### ISSUE THREAD

**Issue by vovel** [novemberfiveco/s3pypi#5]
Boto has a problem with buckets with dots in the name.

https://github.com/boto/boto/issues/2836

It sounds like boto3 does not have this problem.

The directions on

https://novemberfive.co/blog/opensource-pypi-package-repository-tutorial/

imply that the bucket name could (or should) have dots in the name such that it is the same as the hostname from which you pip install packages from. I needed to change the bucket name to a name with no dots in order to successfully upload a package.

**Comment by Owen-Gillespie** [comment]
I also ran into this problem and had to upload the modules to another bucket without dots in the name and then manually copy the files and change the URLs in the index to avoid it
