### ISSUE TITLE
Unable to restrict access using CloudFront WAF template

### ISSUE THREAD

**Issue by ArunaBalasubramanian** [novemberfiveco/s3pypi#51]
@rubenvdb @mdwint  I added a list of static IP ranges to the WhitelistCIDR parameter using the CloudFront WAF template. However, I'm able to install the pip package from the public network (outside the range of IP ranges restricted) destroying the benefit of a private s3 pip server.

I did follow the exact steps mentioned in the blog to create a CloudFormation and S3 bucket.
I have hosted the resources on the eu-west2.

Could you please guide as what is causing this issue?

**Comment by robmcdan** [comment]
I'm having the opposite problem -- used the WAF template and cant access the repo from *any* ip range, despite having set the whitelist CIDR

**Comment by mdwint** [comment]
Closing this because the CloudFormation templates have been replaced by a Terraform configuration.
