### ISSUE TITLE
Error using --dist-path 

### ISSUE THREAD

**Issue by rwedge** [novemberfiveco/s3pypi#60]
I tried using the  `--dist-path` option and got an error that implied it was looking in the dist folder anway:

```python-trace
FileNotFoundError: [Errno 2] No such file or directory: 'dist/<package>.tar.gz'
``` 

I think `Storage.put_package` needs to be updated to use the `dist_path` variable supplied in `Package.create` when it creates the filepath to read in from.

https://github.com/novemberfiveco/s3pypi/blob/a665fabbab95cbbaed9a0cfb3d79eb9b621ca107/s3pypi/storage.py#L49-L55

**Comment by mdwint** [comment]
You're right! Thanks for pointing this out. This feature was not covered by tests yet.

**Comment by rwedge** [comment]
The new release resolved my issue, thanks!
