### ISSUE TITLE
publishing broken as of 0.9.1 release

### ISSUE THREAD

**Issue by Canuteson** [novemberfiveco/s3pypi#62]
s3pypi  --bucket pypi.mydomainbucket --private --force
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'

**Comment by mdwint** [comment]
Do you have the `wheel` package installed? Try installing it with `pip install wheel`, or use the `--no-wheel` option in the s3pypi command.

**Comment by mdwint** [comment]
The `wheel` dependency was recently removed, because tests worked without it... I've added it again now. Thanks for reporting this!

**Comment by Canuteson** [comment]
Thanks for the quick turnaround and release!
