### ISSUE TITLE
PutObject AccessDenied

### ISSUE THREAD

**Issue by kraulin** [novemberfiveco/s3pypi#66]
I have Admin privileges in my AWS account.

I have boto3 installed in a python virtual env so it's isolated.

I have Block Public Access set to `On` on my S3 Bucket.

I have my `~/.aws/credentials`   &&  `~/.aws/config` set up properly 

At the AWS command line I can upload a file to my S3 bucket.

In a python3 interactive command shell, I can walk through a boto3 example and use the put_object method to upload a file.

Using an alternative python script `pip install pypiprivate` in a separate venv because it uses two libraries at different version levels than you, also successfully uploaded a file to my S3 bucket.

----

If I open up public access, I have no trouble at all with issuing a  `s3pypi --bucket bucket_name`.  Works like a charm.  I'll leave it there, set the bucket back to private, and try the same command, and the script will inform me that the package already exists in the repository, so the script has access.

If I try to upload a new package, or a new version of the same package, I'll get the `Access Denied` error.

`(s3pypi_venv) > s3pypi --bucket my_bucket

Traceback (most recent call last):

s3pypi_venv/bin/s3pypi", line 10, in <module>
s3pypi/__main__.py", line 61, in main
s3pypi/__main__.py", line 24, in create_and_upload_package
s3pypi/storage.py", line 55, in put_package   
boto3/resources/factory.py", line 520, in do_action
boto3/resources/action.py", line 83, in __call__
botocore/client.py", line 357, in _api_call   
botocore/client.py", line 661, in _make_api_call

botocore.exceptions.ClientError: An error occurred 
(AccessDenied) when calling the PutObject operation: 
Access Denied`

**Comment by mdwint** [comment]
s3pypi sets the object ACL to `public-read` by default (unless you pass `--private`). Do you have the `s3:PutObjectAcl` permission?

**Comment by jholladay10** [comment]
Also if you have locked access down to the role provided in CloudFormation, it is missing the PutObjectAcl permission.  That will cause the PutObject with an ACL to fail with Access Denied.
