### ISSUE TITLE
Authenticated Access using Lambda@Edge

### ISSUE THREAD

**Issue by chludwig-haufe** [novemberfiveco/s3pypi#67]
Hi,

I have a need for an access-restricted PyPi server on AWS. However, I cannot limit access to certain networks.

Based on your project, I came up with an infrastructure setup that allows access to the S3 bucket _only_ via a CloudFront distribution or if access was granted by a publish or user admin managed policy; the CloudFront distribution checks in a Lambda@Edge function every incoming call for the presence of HTTP basic auth credentials and validates them against a user store in the S3 bucket.

What seemed straight-forward in the beginning turned a bit more complicated when I realized that I had to split the infrastructure definition into multiple CloudFormation stacks for deployment into multiple regions. (CloudFront requires that the Lambda@Edge function is deployed in N. Virginia; company policy requires the S3 bucket is deployed in Frankfurt.)

If you are interested, I can clean up my changes / additions and prepare a pull request at some point next week. (They certainly need some cleaning up - this was the first time I used CloudFormation.) Of course, it's also fine if you think maintaining CloudFormation stacks and code for too many deployment scenarios would overly complicate your setup.

Cheers!
Christoph

**Comment by mdwint** [comment]
Hi, and thanks for reaching out. This certainly would be a valuable addition to the project. I'd be happy to review your changes!
