### ISSUE TITLE
[bug] It is possible to overwrite existing files when using `--dist-path` and having multiple versions in your dist directory.

### ISSUE THREAD

**Issue by gbdlin** [novemberfiveco/s3pypi#79]
Right now, it is possible to implicitly overwrite the package version files when uploading packages using `--dist-path` and having multiple package versions in your `dist` directory.

This is because `s3pypi` checks only the version of the very last file found in the `dist` directory when checking for conflict with existing package versions. This check should happen independently for each package file.

**Comment by mdwint** [comment]
This will be fixed by #76.
